# Generated by Django 4.2.16 on 2025-12-23 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0014_curatedlifemovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movierating',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
