# Generated by Django 4.2.16 on 2025-12-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_movierating_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='movierating',
            name='spoiler',
            field=models.BooleanField(default=False),
        ),
    ]
