# Generated by Django 4.2.16 on 2025-12-23 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DirectMessage',
        ),
    ]
